const projects = [{
  "id": "1",
  "logo": require("./../images/screenshots/weather/logoweatherlogo.png"),
  "name": "weather",
  "link": "link to project weather",
  "desc": "application for monitoring current weather and latest news",
  "overview": [
    "current weather, world news, and local news for many countries",
    "search and save regions of your interest",
    "automatically  recognize your  region",
    "authorization with google account",
    "automatically  recognize time of the day according with sunrise/sunset time,what affects the theme of the app."
  ],
  "slides": [
    require("./../images/screenshots/weather/weather_promo.png"),
    require("./../images/screenshots/weather/weather_promo_night.png"),
    require("./../images/screenshots/weather/209.png"),
    require("./../images/screenshots/weather/210.png"),
    require("./../images/screenshots/weather/211.png"),
    require("./../images/screenshots/weather/213.png"),
    require("./../images/screenshots/weather/215.png"),
    require("./../images/screenshots/weather/216.png"),
    require("./../images/screenshots/weather/217.png"),
    require("./../images/screenshots/weather/218.png"),
    require("./../images/screenshots/weather/219.png"),
    require("./../images/screenshots/weather/220.png"),
    require("./../images/screenshots/weather/221.png"),
    require("./../images/screenshots/weather/222.png")
  ]
},
  {  "id": "2",
    "logo": require("./../images/screenshots/ilcarro/ilcarrplogo.png"),
    "name": "il Carro",
    "link": "link to project ilCarro",
    "desc": "application-aggregator for renting private cars",
    "overview": [
      "offer your car for renting",
      "search relevant car on map or in list using sorting by parameters",
      "see most high-rated cars",
      "book car to the desired date and time in the calendar",
      "manage your rented out cars and bookings in your cabinet",
      "see history of your renting",
      "approve returning car",
      "left feedback and rate cars"
  ],
    "slides": [
    require("./../images/screenshots/ilcarro/ilcarro_promo.png"),
    require("./../images/screenshots/ilcarro/223.png"),
    require("./../images/screenshots/ilcarro/224.png"),
    require("./../images/screenshots/ilcarro/225.png"),
    require("./../images/screenshots/ilcarro/227.png"),
    require("./../images/screenshots/ilcarro/229.png"),
    require("./../images/screenshots/ilcarro/230.png"),
    require("./../images/screenshots/ilcarro/231.png"),
    require("./../images/screenshots/ilcarro/232.png"),
    require("./../images/screenshots/ilcarro/233.png"),
    require("./../images/screenshots/ilcarro/234.png"),
    require("./../images/screenshots/ilcarro/235.png"),
    require("./../images/screenshots/ilcarro/236.png"),
    require("./../images/screenshots/ilcarro/237.png")
  ]
},
  {  "id": "3",
    "logo": require("./../images/screenshots/coffeebreacker/coffee_logo.png"),
    "name": "Coffee Breacker",
    "link": "link to project CoffeeBreacker",
    "desc": "two-side application for coffee house business",
    "overview": [
      "as a client - order coffee and food from one of branches",
      "as a client - see status of your order and history in your account",
      "as a owner - manage menu and branches",
      "as a owner - see statistics",
      "as a owner - see admin’s information",
      "as a owner - manage orders"
  ],
    "slides": [
      require("./../images/screenshots/coffeebreacker/coffee_promo.png"),
      require("./../images/screenshots/coffeebreacker/170.png"),
      require("./../images/screenshots/coffeebreacker/175.png"),
      require("./../images/screenshots/coffeebreacker/176.png"),
      require("./../images/screenshots/coffeebreacker/177.png"),
      require("./../images/screenshots/coffeebreacker/180.png"),
      require("./../images/screenshots/coffeebreacker/182.png"),
      require("./../images/screenshots/coffeebreacker/183.png"),
      require("./../images/screenshots/coffeebreacker/185.png"),
      require("./../images/screenshots/coffeebreacker/186.png"),
      require("./../images/screenshots/coffeebreacker/187.png"),
      require("./../images/screenshots/coffeebreacker/188.png"),
      require("./../images/screenshots/coffeebreacker/189.png"),
      require("./../images/screenshots/coffeebreacker/190.png"),
      require("./../images/screenshots/coffeebreacker/192.png"),
      require("./../images/screenshots/coffeebreacker/193.png"),
      require("./../images/screenshots/coffeebreacker/194.png"),
      require("./../images/screenshots/coffeebreacker/195.png"),
      require("./../images/screenshots/coffeebreacker/196.png"),
      require("./../images/screenshots/coffeebreacker/197.png"),
      require("./../images/screenshots/coffeebreacker/199.png"),
      require("./../images/screenshots/coffeebreacker/202.png"),
      require("./../images/screenshots/coffeebreacker/204.png"),
      require("./../images/screenshots/coffeebreacker/205.png"),
      require("./../images/screenshots/coffeebreacker/206.png")
  ]}
  ];
export {projects}
