const stack = [
    {'name' : 'JavaScript', 'img' : require('./../images/stack/js-file.png'), 'link' :'https://www.w3schools.com/js/'},
    {'name' : 'HTML5', 'img' : require('./../images/stack/html5.png'), 'link' : 'https://www.w3schools.com/html/default.asp'},
    {'name' : 'CSS3', 'img' : require('./../images/stack/css3.png'), 'link' : 'https://www.w3schools.com/css/default.asp'},
    {'name' : 'React', 'img' : require('./../images/stack/react.png'), 'link' : 'https://reactjs.org/docs/add-react-to-a-website.html'},
    {'name' : 'Angular2+', 'img' : require('./../images/stack/angular.png'), 'link' : 'https://angular.io/'},
    {'name' : 'RxJs', 'img' : require('./../images/stack/rxjs.png'), 'link' : 'https://rxjs.dev/'},
    {'name' : 'REST API', 'img' : require('./../images/stack/restapi.png'), 'link' : 'https://restfulapi.net/'},
    {'name' : 'jQuery', 'img' : require('./../images/stack/jquery.png'), 'link' : 'https://jquery.com/'},
    {'name' : 'OpenWeather API', 'img' : require('./../images/stack/open_weather.png'), 'link' : 'https://openweathermap.org/'},
    {'name' : 'News API', 'img' : require('./../images/stack/news_api.png'), 'link' : 'https://newsapi.org/'},
    {'name' : 'Google API', 'img' : require('./../images/stack/googleapi.png'), 'link' : 'https://developers.google.com/apis-explorer'},
    {'name' : 'Google Map API', 'img' : require('./../images/stack/google-maps.png'), 'link' : 'https://developers.google.com/maps'},
    {'name' : 'Git', 'img' : require('./../images/stack/git.png'), 'link' : 'https://git-scm.com/'},
    {'name' : 'i18n', 'img' : require('./../images/stack/i18n.jpg'), 'link' : 'https://www.i18next.com/'},
    {'name' : 'Firebase', 'img' : require('./../images/stack/firebase.png'), 'link' : 'https://firebase.google.com/'},
    {'name' : 'React Testing Library', 'img' : require('./../images/stack/react_testing.png'), 'link' : 'https://testing-library.com/docs/react-testing-library/intro/'},
    {'name' : 'WebStorm', 'img' : require('./../images/stack/webstorm.png'), 'link' : 'https://www.jetbrains.com/ru-ru/webstorm/'},
    {'name' : 'Figma', 'img' : require('./../images/stack/figma.png'), 'link' : 'https://www.figma.com/files/recent?fuid=897100140885675713'},
    {'name' : 'GitHub', 'img' : require('./../images/stack/github.png'), 'link' : 'https://github.com/'},
    {'name' : 'Postman API', 'img' : require('./../images/stack/postman.png'), 'link' : 'https://www.postman.com/'},
    {'name' : 'Bootstrap', 'img' : require('./../images/stack/bootstrap.png'), 'link' : 'https://getbootstrap.com/'},
    {'name' : 'Material Design', 'img' : require('./../images/stack/material_design.png'), 'link' : 'https://m2.material.io/design'},
    {'name' : 'Materialize', 'img' : require('./../images/stack/matcss-min.png'), 'link' : 'https://materializecss.com/'},

];
export {stack}
